name: ds7
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.1=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - executing==2.2.1
      - fonttools==4.61.1
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.5.3
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - numpy==2.4.2
      - pandas==3.0.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.1.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tornado==6.5.4
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.5.3
prefix: /opt/miniconda3/envs/ds7
